# -*- coding: utf-8 -*-
"""HW week 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2NI8RlY9G6vPhIlP9xUfLxNvLSE3wj8
"""

# Read data in
import pandas as pd
races = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-09-07/races.csv")
results = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-09-07/results.csv")
circuits = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-09-07/circuits.csv")

races.head()

results.head()

circuits

df = pd.merge(results, races[['raceId', 'year', 'circuitId', 'date']], on='raceId', how='left')
df = pd.merge(df, circuits[['circuitId', 'name']], on='circuitId', how='left')

df = df[df['year'] > 2015]
df = df.dropna(subset=['grid', 'points'])
df = df[(df['grid'] > 0) & (df['grid'] <= 20)]


print(df.head())

summary = (
    df.groupby(['name', 'grid'])
      .agg(avg_points=('points', 'mean'))
      .reset_index()
)

circuit_counts = (
    summary
    .groupby('name')
    .agg(race_count=('grid', 'count'))
    .reset_index()
)

chosen_circuits = [
    "Circuit de Monaco",
    "Autódromo José Carlos Pace",
    "Baku City Circuit",
    "Silverstone Circuit",
    "Circuit de Spa-Francorchamps"
]

summary_top = summary[summary['name'].isin(chosen_circuits)]

print(summary_top.head())

wide = summary_top.pivot(
    index = 'grid',
    columns = 'name',
    values = 'avg_points'
)

wide

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.lineplot(
    data=summary_top,
    x='grid',
    y='avg_points',
    hue='name',
    marker='o'
)

plt.gca().invert_xaxis()
plt.xticks(range(1, 21))

plt.xlabel('Grid Position (1 = pole)')
plt.ylabel('Average Points')
plt.title('How Starting Position Affects Points Across F1 Circuits')
plt.grid(True)
plt.tight_layout()
plt.show()